### ISSUE TITLE
remove() missing IllegalStateException case

### ISSUE THREAD

**Issue by wit543** [lunaticSKE12/arrayiterator#2]
Please read the [instruction](https://bitbucket.org/skeoop/oop/raw/5be03ec94ed73d8fec5c04dc0485a6e10a12ce95/week2/PA1-ArrayIterator.pdf) carefully.

"If thismethod is called without calling next(). or calledmore than once after calling next(), it throws IllegalStateException."

[remove()](https://github.com/lunaticSKE12/arrayiterator/blob/master/src/ku/util/ArrayIterator.java#L74)

WIT

**Comment by lunaticSKE12** [comment]
add throw IllegalStateException in remove method
